### ISSUE TITLE
Maybe rework the LICENSE?

### ISSUE THREAD

**Issue by LorenzBung** [opinionatedguide/opinionatedguide.github.io-src#22]
I'd happily like to contribute, but following [this guideline](https://opensource.guide/how-to-contribute/#a-checklist-before-you-contribute), I'm sure it would be better if there was a "proper" open-source license.

As mentioned in the LICENSE, the content provided by the contributors themselves is open source. Maybe it is still open source if external resources are used? (Not a legal expert)

I think this would go hand-in-hand with #9 since at least I would be more confident in contributing if there was a proper license.

**Comment by VegaDeftwing** [comment]
Here's the meat of the current license:

> Nobody knows. Let's be real, things like the XKCD's are copyrighted and there's some gray area with some
> of the content with unknown publishers. It's open source and educational material, so I'm realatively
> comfortable claiming fair use and I know the guys at XKCD are cool. But really, don't try to sell this
> as a printed book or anything, for one thing, that's a dick move when it's available online, here, for
> free, for another you'll get sued.

That's on purpose. I know it's crude, but it is also honest. I understand why people would want a good license too (MIT, GPL, etc.) but here's why this isn't that

**Part 1, It's not code**

​	If this were your typically repo on github I'd totally agree with you. The point of most foss licenses is to ensure that no big company can come in, scope up the source, add a large set of features and sell it without giving those features back to the people who wrote the original code base for free. This isn't that. This is a book/guide with content that is meant to be ripped off and shared, and where this being done causes no harm. Further, that's less of a worry to begin with as nobody would want to print or 'steal' this anyway, in part due to lack of a real license. This guide is supposed to remain free,  and if it were to get printed or a pdf sold for profit somewhere else, I do want the ability to force the seller/hoster to either include the GPL (lines 11-17 in the LICENSE file) or take it down.

**Part 2, I'm (probably) not going to actually enforce anything**

​	A license is a contract, and a contract is only as good as it's enforcement. While legal fees are less for me than most (my family is full of lawyers) I have absolutely no intentions of actually trying to enforce a license onto this. The fact of the matter is if some publisher with a death wish decided to actually try to print or sell a copy of this infringement laden mess, that seller would be the one getting sued by the original rights holder, not me.

**Part 3, it's a mess**

> - [17 U.S.C.](https://en.wikipedia.org/wiki/Title_17_of_the_United_States_Code) [§ 107](https://www.law.cornell.edu/uscode/text/17/107)
>
> Notwithstanding the provisions of sections [17 U.S.C.](https://en.wikipedia.org/wiki/Title_17_of_the_United_States_Code) [§ 106](https://www.law.cornell.edu/uscode/text/17/106) and [17 U.S.C.](https://en.wikipedia.org/wiki/Title_17_of_the_United_States_Code) [§ 106A](https://www.law.cornell.edu/uscode/text/17/106A), the fair use of a copyrighted work, including such use by reproduction in copies or phonorecords or by any other means specified by that section, for purposes such as criticism, comment, news reporting, teaching (including multiple copies for classroom use), scholarship, or research, is not an infringement of copyright. In determining whether the use made of a work in any particular case is a fair use the factors to be considered shall include:[[6\]](https://en.wikipedia.org/wiki/Fair_use#cite_note-larson-6)
>
> 1. the purpose and character of the use, including whether such use is of a commercial nature or is for nonprofit educational purposes;
> 2. the nature of the copyrighted work;
> 3. the amount and substantiality of the portion used in relation to the copyrighted work as a whole; and
> 4. the effect of the use upon the potential market for or value of the copyrighted work.
>
> -- https://en.wikipedia.org/wiki/Fair_use#U.S._fair_use_factors

Clearly, this is project heavily relies on point 1., though point 4 does matter here as well.

I have tried to use Creative Commons work as much as I can, but I also know that there are some failings and willful 'content theft' in the gide. The easiest example is the one pointed out in the second sentence: XKCD. On their website:

> If it's a not-for-profit publication, you need no permission -- just print them with attribution to xkcd.com. You can post xkcd in your blog (whether ad-supported or not) with no need to get my permission.

but, clearly XKCD still retains copyright here. What would it mean for OpGuides to adopt a license? Would I be claiming copyright over the XKCDs included? Clearly not. But what about the various logos (Windows, C++, etc.) in /content/openg/ or the images that are not my own (chipsetamd.png, http-status-codes.png, as a few examples) clearly those range from fair use to blatant theft, but I also will not remove them.

**Part 4, copyright law is broken**

Youtube Let's Plays. Memes. Fan Fiction. The list goes on. There are entire industries and Internet subcultures which rely on copyright infringement to survive. Copyright law, in the US, is insane. Rather than spew this all out at you, just watch https://www.youtube.com/watch?v=1Jwo5qc78QU

Alright, now that we're on the same page there, we come to a conclusion here: It doesn't matter.

As long as I don't use images in very bad taste (rip off stock photos, don't attribriute artists, etc.) there are, much, much bigger problems that rights holders have to deal with and there's a NULL chance anyone will ever care. It is by playing on the same rules that the rest of the internet does anyway and being willing to infringe and abuse copyright the content of this guide/book can be better than the currently expensive alternatives it's competing against. All of the currently existing resources held themselves to a higher standard, a pre-internet view of copyright that is unfortunately still law but will be enforced if ever sold or taken to print. This guide exists to provide the best resource it can be, and, yeah, that means 'stealing' some work (doing the best to credit and link back to the source when possible).



I can not put a 'real' license on this because it would be mostly meaningless, would imply that license covers content I don't have the rights to to begin with, and would actually weaken the ability for this guide to remain it's equivalent to FOSS to try to uphold.



The Internet is a crazy place, and I applaud the larger open source community for their work in developing licenses that further FOSS projects. This, by nature, is not a place where one of those licenses matters. We are the pirates and we are encouraging others to plunder our content as well, with the hope that if they do they respect our goals and make it free the same. It is the ethos of hacking, creating, and making on full display that I and any contributors say that for knowledge the license does not matter, as it transcends copyright to begin with.

**Comment by LorenzBung** [comment]
Okay, I'll close this issue then. Might be useful for future questions regarding this topic.
